all:
  children:
    suricata_update_host:
      hosts:
        host1:
            ansible_host: (ip.address)
            ansible_user: (username)
    sensors:
      children:
        software_sensors:
          hosts:
            swsensor1:
              ansible_host: (ip.address)
              ansible_user: (username)
            swsensor2:
              ansible_host: (ip.address)
              ansible_user: (username)
        physical_sensors:
          hosts:
            AP3000-1:
              ansible_host: (ip.address)
              sensor_username: (username)
              UID:
            AP200-1:
              ansible_host: (ip.address)
              sensor_username: (username)
              UID:
        virtual_sensors:
          hosts:
            vSensor1:
              ansible_host: (ip.address)
              sensor_username: (username)
              UID:
  vars:
    fleet_ip: