# For details on how to create encrypted files 
https://docs.ansible.com/ansible/latest/user_guide/vault.html#creating-encrypted-files


# The secrets.yml file contains the following variables:
sensor_password: