---
- hosts: ap200
  gather_facts: no
  
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
    - ./source_files/secrets.yml

  tasks:

  - name:         Create temp/working directory if it does not exist
    file:
      path:       ./temp
      state:      directory
      mode:       '0755'

  - name:         Create source_files/final directory if it does not exist
    file:
      path:       ./source_files
      state:      directory
      mode:       '0755'

  - name:         Check to see if trusted_domains.dat has changed
    copy:
      src:        ./source_files/trusted_domains.dat
      dest:       ./temp/trusted_domains.dat
    delegate_to:  localhost
    register:     trusted

  - name:         Use Corelight-client to upload trusted_domains.csv list to physical and virtual sensors
    command:      corelight-client -b "{{ ansible_host }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate bro input upload --name trusted_domains.dat --file ./source_files/trusted_domains.dat
    delegate_to:  localhost
    when:
      - "'software_sensors' not in group_names"
      - trusted.changed

  - name:         Copy trusted_domains.csv list to Software Sensors
    copy:
      src:            "./source_files/trusted_domains.dat"
      dest:           /etc/corelight/input_files/trusted_domains.dat
      mode:           0644
    when:
      - "'software_sensors' in group_names"
      - trusted.changed
